; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28105.4 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\denis\AppData\Local\Temp\.NETFramework,Version=v4.7.1.AssemblyAttributes.cpp"
